version: 2
updates:
- package-ecosystem: nuget
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 3
  target-branch: development
  reviewers:
  - echarrod
  - davidgrayston
  - MrBurtyyy
  assignees:
  - echarrod
  ignore:
  - dependency-name: Microsoft.VisualStudio.Web.CodeGeneration.Design
    versions:
    - "> 3.0.0"
  - dependency-name: Portable.BouncyCastle
    versions:
    - "> 1.8.5"
